<a href="https://colab.research.google.com/github/LoboSolitario-wp/Python/blob/master/Geolocaliza%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 5.0 MB/s
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.5.post1)
Collecting pyproj>=2.2.0
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 53.2 MB/s
Collecting fiona>=1.8
  Downloading Fiona-1.8.22-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
     |████████████████████████████████| 16.7 MB 807 kB/s
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.3.5)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (22.1.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2022.9.24)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2022.4)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.22 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1

In [4]:
! pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.4)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [5]:
import geopandas as gpds
import pandas as pd

In [10]:
gpds.tools.geocode("Umuarama, São paulo", provider='nominatim', user_agent="my-application")

,geometry,address
0,POINT (-46.78129 -23.56093),"Umuarama, Osasco, Região Imediata de São Paulo..."

In [11]:
df = pd.read_excel('Arquivo.xlsx')
df.head()

,City orig,Country orig,Cyti Dest,Country Dest,Orig real,Dest real
0,Osasco,Brazil,Chicago,USA,"Osasco, Brazil","Chicago, USA"
1,Parauapebas,Brazil,Florianopolis,Brazil,"Parauapebas, Brazil","Florianopolis, Brazil"
2,New York,USA,Parauapebas,Brazil,"New York, USA","Parauapebas, Brazil"

In [16]:
gpds.tools.geocode(df['Orig real'], provider='nominatim', user_agent="my-application")
gpds.tools.geocode(df['Dest real'], provider='nominatim', user_agent="my-application")

,geometry,address
0,POINT (-87.62442 41.87556),"Chicago, Cook County, Illinois, United States"
1,POINT (-48.54961 -27.59730),"Florianópolis, Região Geográfica Imediata de F..."
2,POINT (-49.89033 -6.06968),"Parauapebas, Região Geográfica Imediata de Par..."

In [17]:
df['CoordOrigem'] = gpds.tools.geocode(df['Orig real'], provider='nominatim', user_agent="my-application")['geometry']
df['CoordDestin'] = gpds.tools.geocode(df['Dest real'], provider='nominatim', user_agent="my-application")['geometry']

In [18]:
df.head()

,City orig,Country orig,Cyti Dest,Country Dest,Orig real,Dest real,CoordOrigem,CoordDestin
0,Osasco,Brazil,Chicago,USA,"Osasco, Brazil","Chicago, USA",POINT (-46.79168 -23.53249),POINT (-87.62442 41.87556)
1,Parauapebas,Brazil,Florianopolis,Brazil,"Parauapebas, Brazil","Florianopolis, Brazil",POINT (-49.89033 -6.06968),POINT (-48.54961 -27.59730)
2,New York,USA,Parauapebas,Brazil,"New York, USA","Parauapebas, Brazil",POINT (-74.00602 40.71273),POINT (-49.89033 -6.06968)

In [19]:
df.to_csv('BaseCoord.csv')